// lib/api/mock-db.ts
// Mock database for development - will be replaced with Prisma
export const mockDb = {
  leads: [
    {
      id: '1',
      name: 'דני כהן',
      email: 'danny@company.com',
      phone: '054-1234567',
      company: 'חברת טכנולוגיה',
      source: 'WEBSITE',
      status: 'NEW',
      projectType: 'אתר תדמית',
      estimatedBudget: 15000,
      notes: 'צריכים אתר חדש לחברה',
      userId: 'user_123',
      createdAt: new Date('2024-12-10'),
      updatedAt: new Date('2024-12-10'),
    },
    {
      id: '2',
      name: 'שרה לוי',
      email: 'sara@boutique.com',
      phone: '052-9876543',
      company: 'בוטיק אופנה',
      source: 'PHONE',
      status: 'CONTACTED',
      projectType: 'חנות אונליין',
      estimatedBudget: 25000,
      notes: 'מעוניינת בחנות אונליין',
      userId: 'user_123',
      createdAt: new Date('2024-12-08'),
      updatedAt: new Date('2024-12-12'),
    },
  ],
  
  clients: [
    {
      id: '1',
      name: 'סטארטאפ Y',
      email: 'lior@startup-y.com',
      phone: '054-1234567',
      company: 'Startup Y Ltd.',
      address: 'תל אביב',
      taxId: '123456789',
      type: 'VIP',
      status: 'ACTIVE',
      totalRevenue: 67500,
      userId: 'user_123',
      createdAt: new Date('2024-01-15'),
      updatedAt: new Date('2024-12-01'),
    },
    {
      id: '2',
      name: 'חברת Z',
      email: 'info@company-z.com',
      phone: '03-1234567',
      company: 'Company Z',
      type: 'REGULAR',
      status: 'ACTIVE',
      totalRevenue: 89000,
      userId: 'user_123',
      createdAt: new Date('2024-03-20'),
      updatedAt: new Date('2024-12-05'),
    },
  ],
  
  projects: [
    {
      id: '1',
      name: 'אפליקציית הזמנות',
      description: 'פיתוח אפליקציה למערכת הזמנות',
      type: 'WEB_APP',
      status: 'IN_PROGRESS',
      priority: 'HIGH',
      stage: 'DEVELOPMENT',
      budget: 45000,
      estimatedHours: 120,
      actualHours: 78,
      clientId: '1',
      userId: 'user_123',
      startDate: new Date('2024-11-01'),
      deadline: new Date('2024-12-30'),
      createdAt: new Date('2024-10-25'),
      updatedAt: new Date('2024-12-15'),
    },
  ],
  
  tasks: [],
  timeEntries: [],
  payments: [],
}